#encoding: UTF-8
foods = [{:name => 'Del Valle Antiox Arándano',:UPC => '750155339426',:ingredients => 'agua, jugo de manzana, azucares, extracto de arandano, concentrado del valle sabor arandano',:nutr_score => '1',:econ_score => '',:gastro_score => '',:nutr_advice => '',:econ_advice => '',:gastro_advice => ''},
{:name => 'Jumex Mango (LataBotella)',:UPC => '7501013100037',:ingredients => 'agua, jugo y pulpa de mango, azucares jumex, acido citrico, acido ascorbico',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'a',:nutr_advice => 'advicea',:econ_advice => 'econadvicea',:gastro_advice => 'culinariadvicea'},
{:name => 'Del Valle Frut',:UPC => '7501055330683',:ingredients => 'agua, azucares, concentrado del valle frut (ponche citrico), acido citrico, jugo de naranja del valle, benzoato de potasio, sorbato de potasio, EDTA de calcio,colorante amarillo 5, colorante amarrillo 6, tiamina, retinol',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'b',:nutr_advice => 'adviceb',:econ_advice => 'econadviceb',:gastro_advice => 'culinariadviceb'},
{:name => 'Nesquik Nestle (cajita)',:UPC => '75000011',:ingredients => 'leche parcialmente descremada, azucar, fibra dietetica, cocoa, celulosa microcristalina, carboxil metilcelulosa, sabor natural a chocolate, sal yodada, carragenina, mono y digliceridos de acidos grasos, suclalosa, acelsufame K, canela, vitamina C, niacina, vitamina E, vitamina B2, vitamina B6, vitamina A, vitamina B1, acido folico,vitamina D, vitamina B12  ',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'c',:nutr_advice => 'advicec',:econ_advice => 'econadvicec',:gastro_advice => 'culinariadvicec'},
{:name => 'Nesquik Nestle (sport)',:UPC => '7501059236233',:ingredients => 'leche parcialmente descremada, azucar, cocoa, celulosa microcristalina, carboxilmetilcelulosa, sal yodada, carragenina, mono y digliceridos de acidos grasos, saborizante artificial, suclalosa, acelsufame K, canela, vitamina C, niacina, vitamina E, vitamina B2, vitamina B6, vitamina A, vitamina B1, acido folico, vitamina D, vitamina B12  ',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'd',:nutr_advice => 'adviced',:econ_advice => 'econadviced',:gastro_advice => 'culinariadviced'},
{:name => 'Peñafiel Agua Mineral ',:UPC => '7501073830509',:ingredients => 'agua, gas ',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'e',:nutr_advice => 'advicee',:econ_advice => 'econadvicee',:gastro_advice => 'culinariadvicee'},
{:name => 'Coca Cola',:UPC => '7501055328345',:ingredients => 'agua carbonadata, azucares, concentrados coca cola, ',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'f',:nutr_advice => 'advicef',:econ_advice => 'econadvicef',:gastro_advice => 'culinariadvicef'},
{:name => 'Be ligtht sabor mango ',:UPC => '7501011167063',:ingredients => 'agua, acido citrico, concentrado Be light mando, exametafosfato de sodio, acido malico, aspartame, acelsulfame, sorbato de potasio, citrato de sodio, EDTA de calcio, caramelo, acido ascorbico, tartracina, amarillo ocaso FCF, rojo allura AC, fenil cetunuricos, fenilalanina ',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'g',:nutr_advice => 'adviceg',:econ_advice => 'econadviceg',:gastro_advice => 'culinariadviceg'},
{:name => 'Bonafont levite fresa',:UPC => '75810400223',:ingredients => 'agua, azucares, acido citrico, saborizante  indentio al natural fresa, acido malico, sorbato de potasio, citrato de sodio, estevia, polidimetilsiloxano, puede contener trazas de soya, puede contener trazas de maiz ',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'h',:nutr_advice => 'adviceh',:econ_advice => 'econadviceh',:gastro_advice => 'culinariadviceh'},
{:name => 'Bonafont Jamaica',:UPC => '75810400294',:ingredients => 'agua, azucares, acido citrico, acido tartarico,extracto de flor de jamaica, sabor natural identico al natural jamaica , benzoato de sodio, citrato de sodio, sorbato de potasio, estevia, rojo allura, EDTA de calcio, polidimetisiloxan, color caramelo clase VI, colorante azul 1, puede contener trazas de soya, puede contoner trazas de maiz',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'i',:nutr_advice => 'advicei',:econ_advice => 'econadvicei',:gastro_advice => 'culinariadvicei'},
{:name => 'Bonafont jugo de manzana ',:UPC => '75810400257',:ingredients => 'agua, azucares, jugo concentrado de manzana, acido malico, saborizante identico al natural manzana, benzoato de sodio, acido citrico, sorbato de potasio, citrato de sodio, colrante, estevia, EDA de calcioy polidimetilsiloxano',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'j',:nutr_advice => 'advicej',:econ_advice => 'econadvicej',:gastro_advice => 'culinariadvicej'},
{:name => 'Bonafont kids jugo de uva',:UPC => '75038663',:ingredients => 'agua, azucares, jugo concentrado de uva, acido citrico, acito tartarico, saborizante identico al natural uva, benzoato de sodio, antosianina, sorbato de potasio, citrato de sodio, estevia, EDTA de calcio, polimitelsiloxano, puede contener trazas de soya, puede contener trazas de maiz',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'k',:nutr_advice => 'advicek',:econ_advice => 'econadvicek',:gastro_advice => 'culinariadvicek'},
{:name => 'Leche Alpura Vainilla',:UPC => '75002091',:ingredients => 'leche semidescremada rehidratada, azucar, fosfato hidrogenado disodico, saborizantes artificiales, carragenina, lactasa, sucralosa, acelsufame,colorante amarillo 3, colorante amarillo 4, niacina, pantotenato de calcio, vitamina B6, vitamina B2, vitamina B1, Vitamina A, yoduro de potasio, acido folico, vitamina K1, biotina, vitamina D, vitamina B12',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'lm',:nutr_advice => 'advicelm',:econ_advice => 'econadvicelm',:gastro_advice => 'culinariadvicelm'},
{:name => 'All-Bran chocolate kellogg´s',:UPC => '7501008072264',:ingredients => 'leche parcialmente descremada, azúcar, inulina, cocoa, fibra dietetica (polidextrosa), harina de arroz, saborizante artificial a chocolate, fosfato hidrogenado disodico, fosfato trisodico, polifosfato de sodio, citrato trisodico, carragenina, vitamina C (ascorbato de sodio), maltodextrina, niacina (niacinamida), vitamina B6 (pridoxina), folacina (acido folico), vitamina A (palmitato), Clorhidrato de tiamina (Vitamina B1), vitamina D (colecalciferol), riboflavina (vitamina B2), vitamina B12 (cobalamina) ',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'no',:nutr_advice => 'adviceno',:econ_advice => 'econadviceno',:gastro_advice => 'culinariadviceno'},
{:name => 'Hershey´s chocolate',:UPC => '7501024579327',:ingredients => 'leche descremada rehidratada, azucar, cocoa, grasa butirica, mondigliceridos, cocoa alcalinizada, saborizante artificial, fosfato hidrogenadodisodico, carbonato de calcio, sal yodatada, estevia, goma guar, carregenina, vitamina B2, vitamina B1, vitamina A,  vitamina D, vitamina E, zinc ',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'p',:nutr_advice => 'advicep',:econ_advice => 'econadvicep',:gastro_advice => 'culinariadvicep'},
{:name => 'Alpura Clasica 2000',:UPC => '7501055902040',:ingredients => 'leche, vitamina A, vitamina D3, ',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'q',:nutr_advice => 'adviceq',:econ_advice => 'econadviceq',:gastro_advice => 'culinariadviceq'},
{:name => 'Bonafont Natural',:UPC => '75810400171',:ingredients => 'agua',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'r',:nutr_advice => 'advicer',:econ_advice => 'econadvicer',:gastro_advice => 'culinariadvicer'},
{:name => 'Jomi Lala Fresa',:UPC => '75042684',:ingredients => 'leche semidescremada de vaca, azucar y/o fructuosa, saborizante, carboxilmetilcelulosa,  citrado de sodio, fosfato disodico, carregenina, colorante rojo 40, estevia, Niacina (acido nicotinico), vitamina A (retinol), vitamina B5 (acido pantotenico), vitamina D, vitamina B12, acido folico.',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 't',:nutr_advice => 'advicet',:econ_advice => 'econadvicet',:gastro_advice => 'culinariadvicet'},
{:name => 'Jomi Lala Vainilla',:UPC => '75042691',:ingredients => 'leche semidescremada de vaca, azucar y/o fructuosa, saborizante, carboxilmetilcelulosa, citrado de sodio, fosfato disodico, carregenina, estevia,colorante amarillo 6, colorante amarillo 5 (tartazina). Niacina (acido nicotinico), vitamina A (retinol), vitamina B5 (acido pantotenico), vitamina D, vitamina B12,acido folico',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'y',:nutr_advice => 'advicey',:econ_advice => 'econadvicey',:gastro_advice => 'culinariadvicey'},
{:name => 'Ades Guanabana',:UPC => '7501005114530',:ingredients => 'base de soya (agua y semillas de soya seleccionadas), azucares, pulpa de guanabana, maltodextrina, pectina, acido citrico, saborizante identico al natural guanabana, vitamina C, vitamina B1, vitamina B2, vitamina B6,  vitamina B12, niacina, acido folico, hierro, zinc, cloruro de calcio, colorante natural carmin, suclalosa, acelsufame K',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'u',:nutr_advice => 'adviceu',:econ_advice => 'econadviceu',:gastro_advice => 'culinariadviceu'},
{:name => 'Ades Uva',:UPC => '7501005109079',:ingredients => 'base de soya (agua y semillas de soya seleccionadas), azucares, jugo de concentrado de uva, maltodextrina, pectina, acido citrico, saborizante identico al natural de uva, vitamina C, vitamina B1, vitamina B2, vitamina B6,  vitamina B12, niacina, acido folico, hierro, zinc, cloruro de calcio, colorante natural carmin, suclalosa ',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'y',:nutr_advice => 'advicey',:econ_advice => 'econadvicey',:gastro_advice => 'culinariadvicey'},
{:name => 'Nectar Mango Del Valle',:UPC => '7501055335961',:ingredients => 'agua, jugo y pulpa de mango concentrado, azucares, concentrado del valle sabor mango ',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'aa',:nutr_advice => 'adviceaa',:econ_advice => 'econadviceaa',:gastro_advice => 'culinariadviceaa'},
{:name => 'Boing Uva',:UPC => '75001834',:ingredients => 'Agua, jugo de uva, acido cítrico, color natural caramelo clase IV, saborizante artificial, colorante artificial Rojo 40 ,colorante artificial Azul 1, benzoato de sodio, vitamina A (Retino), vitamina B1 (Tiamina), vitamina C (Acido ascórbico), calcio, hierro ',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'z',:nutr_advice => 'advicez',:econ_advice => 'econadvicez',:gastro_advice => 'culinariadvicez'},
{:name => 'Boing Mango',:UPC => '75001759',:ingredients => 'Agua, pulpa de mango, azúcar, acido cítrico, sorbitol, lecitina, colorante natural Carmín , beta-carotenos, eritorbato de sodio, benzoato de sodio,sorbato de potasio, Vitamina A (Retinol), vitamina B1 (Tiamina),vitamina C (Acido ascórbico), calcio,hierro',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'aa',:nutr_advice => 'adviceaa',:econ_advice => 'econadviceaa',:gastro_advice => 'culinariadviceaa'},
{:name => 'Boing Naranja',:UPC => '75001803',:ingredients => 'agua, jugo de naranja, azúcar, acido cítrico, ester de glicerol de madera de resina, almidón modificado, aceite esencial de naranja, colorante artificial amarillo 5, colorante artificial amarillo 6, carboximetilcelulosa, goma guar, eritorbato sódico, vitamina A (retinol),vitamina B1 (Ttiamina), vitamina C (acido ascórbico), calcio,hierro ',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'a',:nutr_advice => 'advicea',:econ_advice => 'econadvicea',:gastro_advice => 'culinariadvicea'},
{:name => 'Boing Fresa',:UPC => '75001766',:ingredients => 'agua, pulpa de fresa, azúcar, acido cítrico, sorbitol. Lecitina, colorante artificial rojo 40,colorante artificial Amarillo 5,colorante artificial Amarrillo 6,colorante artificial Azul 1, saborizante artificial, benzoato de sodio, sorbato de potasio, vitamina A(Retinol), vitamina B1(Tiamina),vitamina C (Acido ascórbico), calcio,hierro ',:nutr_score => '2',:econ_score => 'advice',:gastro_score => 'b',:nutr_advice => 'adviceb',:econ_advice => 'econadviceb',:gastro_advice => 'culinariadviceb'},
{:name => 'Boing Guayaba',:UPC => '75001773',:ingredients => 'agua, pulpa de guayaba, azúcar, acido cítrico, sorbitol, lecitina, colorante natural (carmín), benzoato de sodio, sorbato de potasio, vitamina A (retinol), vitamina B1 (Tiamina),vitamina C (acido ascórbico), calcio, hierro ',:nutr_score => '3',:econ_score => 'advice',:gastro_score => 'c',:nutr_advice => 'advicec',:econ_advice => 'econadvicec',:gastro_advice => 'culinariadvicec'},
{:name => 'Boing jugo de manzana',:UPC => '75001797',:ingredients => 'agua, jugo de  manzana, azúcar, Acido cítrico, colorantes artificial Amarillo 5, colorante artificial Rojo 4,colorante artificial Azul 1, saborizante artificial, benzoato de sodio, vitamina A (retinol),vitamina B1 (Tiamina), vitamina C (Acido ascórbico), calcio,hierro. ',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'd',:nutr_advice => 'adviced',:econ_advice => 'econadviced',:gastro_advice => 'culinariadviced'},
{:name => 'All-Bran sabor vainilla ',:UPC => '7501008072301',:ingredients => 'leche parcialmente descremada, azucar, inulina, fibra dietica (polidextrosa), harina de arroz, saborizante artificial a vainilla, fostato hidrogenado disodico, fosfato trisodico, polifosfato de sodio, citrato trisodico, carragenina, vitamina C (ascorbato de sodio), maltodextrina, niacina (niacinamida), vitamina B6 (pridoxina), folacina (acido folico) vitamina A (palmitato), tiamina (clorhidrato, vitamina B1), vitamina D (colecalciferol), riboflavina (vitamina B2), vitamina B12 (cobalamina) ',:nutr_score => '1',:econ_score => 'advice',:gastro_score => 'e',:nutr_advice => 'advicee',:econ_advice => 'econadvicee',:gastro_advice => 'culinariadvicee'},
]
foods.each do |food|
	Food.create!(food)
end

ingredients = [{:name=>'sorbato de potasio', :adv1=>'Aceite aromático extraido de la planta', :adv2=>'Puede que ayude a prevenir la fibromalgia', :adv3=>'Pariente del crémor tártaro usado en cocina', :adv4=>'Se usan almidones modificados para crear adhesivos', :adv5=>'Algunos se usan para crear papel, planchar ropa'},
{:name=>'sabor natural a chocolate', :adv1=>'Edulcorante también conocido como acelsulfame-K', :adv2=>'Mejor conocido como acelsulfamo-k, endulza tus alimentos sin calorías', :adv3=>'Edulcorante artificial 200 veces más dulce que el azúcar', :adv4=>'Edulcorante artificial favorito en cocina y bebidas carbonatadas', :adv5=>'Considerado seguro por autoridades, no se recomienda consumir en exceso'},
{:name=>'carragenina', :adv1=>'Edulcorante también conocido como acelsufame', :adv2=>'Mejor conocido como acelsulfamo-k, endulza tus alimentos sin calorías', :adv3=>'Edulcorante artificial 200 veces más dulce que el azúcar', :adv4=>'Edulcorante artificial favorito en cocina y bebidas carbonatadas', :adv5=>'Considerado seguro por autoridades, no se recomienda consumir en exceso'},
{:name=>'acelsulfame', :adv1=>'Edulcorante también conocido como acelsufame', :adv2=>'Mejor conocido como acelsulfamo-k, endulza tus alimentos sin calorías', :adv3=>'Edulcorante artificial 200 veces más dulce que el azúcar', :adv4=>'Edulcorante artificial favorito en cocina y bebidas carbonatadas', :adv5=>'Considerado seguro por autoridades, no se recomienda consumir en exceso'},
{:name=>'citrato de sodio', :adv1=>'Vitamina C', :adv2=>'Importante para huesos y dientes', :adv3=>'Protege contra infecciones', :adv4=>'¡Muy saludabe!', :adv5=>'Su falta produce escorbuto'},
{:name=>'benzoato de sodio', :adv1=>'Es un acidulante que se usa para mejorar la sensación de dulzura y el sabor', :adv2=>'Es un antioxidante que ayuda a manter en buen estado los alimentos', :adv3=>'Se obtiene del jugo de frutas cìtricas, o fermentando azúcares', :adv4=>'Muy buen conservador usado en el envasado de alimentos', :adv5=>''},
{:name=>'acido citrico', :adv1=>'Es un acidulante que se usa para mejorar la sensación de dulzura y el sabor', :adv2=>'Es un antioxidante que ayuda a manter en buen estado los alimentos', :adv3=>'Se obtiene del jugo de frutas cìtricas, o fermentando azúcares', :adv4=>'Muy buen conservador usado en el envasado de alimentos', :adv5=>''},
{:name=>'sucralosa', :adv1=>'Otro nombre de la vitamina B9', :adv2=>'Vitamina muy importante durante el embarazo', :adv3=>'Ayuda a la formación de glóbulos rojos en tu organismo', :adv4=>'Vitamina B6 con la que se fortifican muchas harinas y panes', :adv5=>'Esta vitamina puede proteger de algunos tipos de anemias'},
{:name=>'saborizante artificial a chocolate', :adv1=>'Otro nombre de la vitamina B9', :adv2=>'Vitamina muy importante durante el embarazo', :adv3=>'Ayuda a la formación de glóbulos rojos en tu organismo', :adv4=>'Vitamina B6 con la que se fortifican muchas harinas y panes', :adv5=>'Esta vitamina puede proteger de algunos tipos de anemias'},
{:name=>'saborizante artificial', :adv1=>'Ácido presente naturalmente en manzanas', :adv2=>'Se usa para balancear la dulzura de alimentos', :adv3=>'Usado en refrescos, mermeladas de fruta y jaleas', :adv4=>'Está en las uvas, mejora el sabor del vino', :adv5=>'Puede que ayude a prevenir la fibromalgia'},
{:name=>'carregenina', :adv1=>'Proviene de uvas, bananas y tamarindos', :adv2=>'Mejora el sabor y funciona como conservador natural', :adv3=>'Pariente del crémor tártaro usado en cocina', :adv4=>'', :adv5=>'Además de en alimentos, se usa en fotografía y barnices'},
{:name=>'saborizante identico al natural guanabana', :adv1=>'Proviene de uvas, bananas y tamarindos', :adv2=>'Mejora el sabor y funciona como conservador natural', :adv3=>'Pariente del crémor tártaro usado en cocina', :adv4=>'', :adv5=>'Además de en alimentos, se usa en fotografía y barnices'},
{:name=>'saborizante identico al natural de uva', :adv1=>'Líquido sin sabor, color u olor propio', :adv2=>'Principal ingrediente de muchos alimentos', :adv3=>'Conocido como el "solvente universal"', :adv4=>'Es muy saludable beber 2 lt. De agua natural al día', :adv5=>''},
{:name=>'colorante artificial Azul 1', :adv1=>'Agua con dióxido de carbono diluído', :adv2=>'Es muy ùtil para eliminar manchas de café o de vino tinto', :adv3=>'Desde el siglo XVIII se bebe como refresco', :adv4=>'Se usa como remedio para la indigestión', :adv5=>'A veces se le llama "soda", o "agua soda"'},
{:name=>'colorante natural Carmín', :adv1=>'Usado para espesar líquidos en alimentos procesados', :adv2=>'Algunos se usan para crear papel, planchar ropa', :adv3=>'Se usan almidones modificados para crear adhesivos', :adv4=>'Considerados seguros, aún tienen polémica respecto a su efecto en salud', :adv5=>''},
{:name=>'aceite esencial de naranja', :adv1=>'Conocido como amarillo crepúsculo, ocaso o no. 6', :adv2=>'Usado sobre todo en mermeladas o galletas', :adv3=>'Hay reportes de alergias y efectos a la salud sin confirmar', :adv4=>'Es un derivado del petróleo', :adv5=>'Hay campañas para eliminarlo de bebidas y alimentos en Europa'},
{:name=>'colorante artificial Amarillo 5', :adv1=>'Usado sobre todo en mermeladas o galletas', :adv2=>'Principal ingrediente de muchos alimentos', :adv3=>'Usado en refrescos, mermeladas de fruta y jaleas', :adv4=>'Vitamina B6 con la que se fortifican muchas harinas y panes', :adv5=>'Puede que ayude a prevenir la fibromalgia'},
{:name=>'colorante natural (carmín)', :adv1=>'Sustituto de azúcar muy usado en productos no horneados', :adv2=>'Este sustituto de azúcar es destruído a altas temperaturas', :adv3=>'Los fenilcetianúricos no deben consumir esto', :adv4=>'Ha sufrido de difamación, pero es considerado seguro', :adv5=>''},
{:name=>'fostato hidrogenado disodico', :adv1=>'Si se refiere a la de mesa, es  la sucralosa', :adv2=>'Cada persona consume al año  más de 20 kg al año en promedio', :adv3=>'No abuses: Se relaciona con la obesidad y la diabetes', :adv4=>'', :adv5=>''}
]

ingredients.each do |ingredient|
	Ingredient.create!(ingredient)
end

Role.create([
  { :name => 'banned' }, 
  { :name => 'registered' }, 
  { :name => 'score' },
  { :name => 'information' },
  { :name => 'allinfo' },
  { :name => 'admin'}
], :without_protection => true)
user = User.create! :name => 'User1', :email => 'user@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user.name
user2 = User.create! :name => 'User2', :email => 'user2@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user2.name
user3 = User.create! :name => 'User3', :email => 'score@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user3.name
user4 = User.create! :name => 'User4', :email => 'information@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user4.name
user5 = User.create! :name => 'User5', :email => 'allinfo@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user5.name
user.add_role :admin
user3.add_role :score
user4.add_role :information
user5.add_role :allinfo
user.remove_role :registered
user3.remove_role :registered
user4.remove_role :registered
user5.remove_role :registered
